# $NetBSD$

DISTNAME=	config-R2023-0.12
CATEGORIES=	local-mef

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Meta package for 2023

META_PACKAGE=	yes

DEPENDS+=	zathura-[0-9]*:../../print/zathura
DEPENDS+=	feh-[0-9]*:../../graphics/feh
DEPENDS+=	dwm-[0-9]*:../../wm/dwm
DEPENDS+=	p5-Crypt-RandPasswd-[0-9]*:../../security/p5-Crypt-RandPasswd
DEPENDS+=	rpm-[0-9]*:../../misc/rpm
DEPENDS+=	ttyrec-[0-9]*:../../misc/ttyrec
DEPENDS+=	ksh93-[0-9]*:../../shells/ksh93
DEPENDS+=	qemu-[0-9]*:../../emulators/qemu
DEPENDS+=	mlterm-[0-9]*:../../x11/mlterm

DEPENDS+=	py-asciinema--[0-9]*:../misc/py-asciinema

.include "../../mk/bsd.pkg.mk"
