# $NetBSD$

DISTNAME=	config-R2023-0.1
CATEGORIES=	local-mef

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Meta package for 2023

META_PACKAGE=	yes

DEPENDS+=	zathura-[0-9]*:../../print/zathura
DEPENDS+=	feh-[0-9]*:../../graphics/feh

.include "../../mk/bsd.pkg.mk"
