# $NetBSD$

DISTNAME=       config-xen-0.01
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        Meta package for monitoring machine

META_PACKAGE=   yes

DEPENDS+= xentools45-[0-9]*:../../sysutils/xentools45
DEPENDS+= xentools48-[0-9]*:../../sysutils/xentools48
DEPENDS+= xenkernel45-[0-9]*:../../sysutils/xenkernel45
DEPENDS+= xenkernel48-[0-9]*:../../sysutils/xenkernel48

.include "../../mk/bsd.pkg.mk"
