# $NetBSD$

DISTNAME=       config-chat-0.01
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        Meta package for recent interest

META_PACKAGE=   yes

DEPENDS+= ircII-[0-9]*:../../chat/ircII
DEPENDS+= icb-[0-9]*:../../chat/icb

.include "../../mk/bsd.pkg.mk"
