# $NetBSD$

DISTNAME=	config-www-0.3
CATEGORIES=	meta-pkgs

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Meta package for Ham Radio

META_PACKAGE=	yes

DEPENDS+=	moodle-[0-9]*:../../www/moodle
DEPENDS+=	postgresql17-server-[0-9]*:../../databases/postgresql17-server
DEPENDS+=	php84-[0-9]*:../../lang/php84

.include "../../mk/bsd.pkg.mk"
