# $NetBSD$

DISTNAME=       test-mail-claws-mail-0.01
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        claws-mail meta package for test

META_PACKAGE=   yes

BUILD_DEPENDS+=	claws-mail-[0-9]*:../../mail/claws-mail
BUILD_DEPENDS+=	claws-mail-archive-[0-9]*:../../mail/claws-mail-archive
BUILD_DEPENDS+=	claws-mail-attachwarner-[0-9]*:../../mail/claws-mail-attachwarner
BUILD_DEPENDS+=	claws-mail-att-remover-[0-9]*:../../mail/claws-mail-attremover
BUILD_DEPENDS+=	claws-mail-bogofilter-[0-9]*:../../mail/claws-mail-bogofilter
BUILD_DEPENDS+=	claws-mail-cachesaver-[0-9]*:../../mail/claws-mail-cachesaver
BUILD_DEPENDS+=	claws-mail-fetchinfo-[0-9]*:../../mail/claws-mail-fetchinfo
BUILD_DEPENDS+=	claws-mail-mailmbox-[0-9]*:../../mail/claws-mail-mailmbox
BUILD_DEPENDS+=	claws-mail-managesieve-[0-9]*:../../mail/claws-mail-managesieve
BUILD_DEPENDS+=	claws-mail-newmail-[0-9]*:../../mail/claws-mail-newmail
BUILD_DEPENDS+=	claws-mail-notification-[0-9]*:../../mail/claws-mail-notification
BUILD_DEPENDS+=	claws-mail-pgp-[0-9]*:../../mail/claws-mail-pgp
BUILD_DEPENDS+=	claws-mail-pgpcore-[0-9]*:../../mail/claws-mail-pgpcore
BUILD_DEPENDS+=	claws-mail-pgpinline-[0-9]*:../../mail/claws-mail-pgpinline
BUILD_DEPENDS+=	claws-mail-pgpmime-[0-9]*:../../mail/claws-mail-pgpmime
BUILD_DEPENDS+=	claws-mail-rssyl-[0-9]*:../../mail/claws-mail-rssyl
BUILD_DEPENDS+=	claws-mail-smime-[0-9]*:../../mail/claws-mail-smime
BUILD_DEPENDS+=	claws-mail-spamassassin-[0-9]*:../../mail/claws-mail-spamassassin
BUILD_DEPENDS+=	claws-mail-spam-report-[0-9]*:../../mail/claws-mail-spamreport
BUILD_DEPENDS+=	claws-mail-synce_plugin-[0-9]*:../../mail/claws-mail-synce
BUILD_DEPENDS+=	claws-mail-tnef-parse-[0-9]*:../../mail/claws-mail-tnef
BUILD_DEPENDS+=	claws-mail-vcalendar-[0-9]*:../../mail/claws-mail-vcalendar
BUILD_DEPENDS+=	clawsker-[0-9]*:../../mail/clawsker                 

.include "../../mk/bsd.pkg.mk"
