# $NetBSD$

DISTNAME=	config-multimedia-0.01
CATEGORIES=	local-mef

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Meta package for multimedia

META_PACKAGE=	yes

DEPENDS+=	mplayer-[0-9]*:../../multimedia/mplayer
DEPENDS+=	ffmpeg4-[0-9]*:../../multimedia/ffmpeg4

.include "../../mk/bsd.pkg.mk"
