# $NetBSD$

DISTNAME=	config-audio-0.01
CATEGORIES=	meta-pkgs

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Meta package for audio stuff

META_PACKAGE=	yes

DEPENDS+=	audacity-[0-9]*:../../audio/audacity

.include "../../mk/bsd.pkg.mk"
