# $NetBSD$

DISTNAME=	config-selenium-2026.03
CATEGORIES=	meta-pkgs

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Meta package for Selenium

META_PACKAGE=	yes

DEPENDS+=	geckodriver-[0-9]*:../../www/geckodriver
DEPENDS+=	p5-Test-WWW-Selenium-[0-9]*:../../devel/p5-Test-WWW-Selenium
DEPENDS+=	nodejs-[0-9]*:../../lang/nodejs

.include "../../mk/bsd.pkg.mk"
