# $NetBSD$

DISTNAME=	config-selenium-2026.04
CATEGORIES=	meta-pkgs

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Meta package for Selenium

META_PACKAGE=	yes

DEPENDS+=	geckodriver-[0-9]*:../../www/geckodriver
DEPENDS+=	p5-Test-WWW-Selenium-[0-9]*:../../devel/p5-Test-WWW-Selenium
DEPENDS+=	nodejs-[0-9]*:../../lang/nodejs
DEPENDS+=	p5-Selenium-Remote-Driver-[0-9]*:../../wip/p5-Selenium-Remote-Driver

.include "../../mk/bsd.pkg.mk"
