# $NetBSD$

DISTNAME=       config-minimum-0.2
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        Meta package for monitoring machine

META_PACKAGE=   yes

DEPENDS+= emacs-desktop-[0-9]*:../../local-mef/emacs-desktop
DEPENDS+= firefox-[0-9]*:../../www/firefox
DEPENDS+= fvwm-[0-9]*:../../wm/fvwm
DEPENDS+= wpa_gui-[0-9]*:../../net/wpa_gui

.include "../../mk/bsd.pkg.mk"
