# $NetBSD$

DISTNAME=       config-desktop-0.06
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        Minimum set of Desktop

DEPENDS+= emacs-desktop-[0-9]*:../../local-mef/emacs-desktop

DEPENDS+= firefox-[0-9]*:../../www/firefox
DEPENDS+= gimp-[0-9]*:../../graphics/gimp
DEPENDS+= libreoffice-[0-9]*:../../misc/libreoffice
DEPENDS+= samba-[0-9]*:../../net/samba

DEPENDS+= rsync-[0-9]*:../../net/rsync
DEPENDS+= screen-[0-9]*:../../misc/screen
DEPENDS+= zsh-[0-9]*:../../shells/zsh
DEPENDS+= sudo-[0-9]*:../../security/sudo
DEPENDS+= perl-[0-9]*:../../lang/perl5
DEPENDS+= pkglint-[0-9]*:../../pkgtools/pkglint
DEPENDS+= pkgin-[0-9]*:../../pkgtools/pkgin
DEPENDS+= git-base-[0-9]*:../../devel/git-base
DEPENDS+= git-gitk-[0-9]*:../../devel/git-gitk
DEPENDS+= wget-[0-9]*:../../net/wget


DEPENDS+= fvwm-[0-9]*:../../wm/fvwm
DEPENDS+= sendmail-[0-9]*:../../mail/sendmail
DEPENDS+= inkscape-[0-9]*:../../graphics/inkscape
DEPENDS+= xlockmore-[0-9]*:../../x11/xlockmore

DEPENDS+= xpdf-[0-9]*:../../print/xpdf
DEPENDS+= wpa_gui-[0-9]*:../../net/wpa_gui
DEPENDS+= ja-ptex-[0-9]*:../../wip/ja-ptex

DEPENDS+= php-[0-9]*:../../lang/php72
DEPENDS+= gnuplot-[0-9]*:../../graphics/gnuplot

META_PACKAGE=   yes

.include "../../mk/bsd.pkg.mk"
