# $NetBSD$

DISTNAME=       config-set-2024.0202
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        All set

DEPENDS+=	config-desktop-[0-9]*:../../local-mef/config-desktop
DEPENDS+=	config-audio-[0-9]*:../../local-mef/config-audio
DEPENDS+=	emacs-desktop-[0-9]*:../../local-mef/emacs-desktop
DEPENDS+=	config-cad-[0-9]*:../../local-mef/config-cad
DEPENDS+=	config-devel-[0-9]*:../../local-mef/config-devel
DEPENDS+=	config-monitor-[0-9]*:../../local-mef/config-monitor
DEPENDS+=	config-more-[0-9]*:../../local-mef/config-more
DEPENDS+=	config-latex-[0-9]*:../../local-mef/config-latex
DEPENDS+=	config-graphics-[0-9]*:../../local-mef/config-graphics
DEPENDS+=	config-R2021-[0-9]*:../../local-mef/config-R2021
DEPENDS+=	config-R2022-[0-9]*:../../local-mef/config-R2022
DEPENDS+=	config-R2023-[0-9]*:../../local-mef/config-R2023
DEPENDS+=	config-R2024-[0-9]*:../../local-mef/config-R2024
DEPENDS+=	config-databases-[0-9]*:../../local-mef/config-databases

DEPENDS+=	check-update-prerequisite-[0-9]*:../../local-mef/check-update-prerequisite

META_PACKAGE=   yes

.include "../../mk/bsd.pkg.mk"
