# $NetBSD$

DISTNAME=       config-set-0.01
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        All set

DEPENDS+=	config-desktop-[0-9]*:../../local-mef/config-desktop
DEPENDS+=	emacs-desktop-[0-9]*:../../local-mef/emacs-desktop
DEPENDS+=	config-cad-[0-9]*:../../local-mef/config-cad
DEPENDS+=	config-devel-[0-9]*:../../local-mef/config-devel
DEPENDS+=	config-monitor-[0-9]*:../../local-mef/config-monitor
DEPENDS+=	config-more-[0-9]*:../../local-mef/config-more

DEPENDS+=	check-update-prerequisite-[0-9]*:../../local-mef/check-update-prerequisite

META_PACKAGE=   yes

.include "../../mk/bsd.pkg.mk"
