# $NetBSD$

DISTNAME=       config-graphics-0.01
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://github.com/makoto-fujiwara/local-mef/config-graphics
COMMENT=        Small set of graphics packages

DEPENDS+=	p5-SVG-[0-9]*:../../graphics/p5-SVG
DEPENDS+=	xv-[0-9]*:../../graphics/xv


META_PACKAGE=   yes

.include "../../mk/bsd.pkg.mk"
