# $NetBSD$

DISTNAME=       config-latex-0.02
CATEGORIES=     local-mef
MASTER_SITES=   http://cvsweb.ki.nu/mef/personal-pkgsrc
DISTFILES=      # empty

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        Set for Office work

META_PACKAGE=	yes
DEPENDS+=	tex-rsfs-[0-9]*:../../fonts/tex-rsfs
DEPENDS+=	tex-psnfss-[0-9]*:../../fonts/tex-psnfss
DEPENDS+=	tex-paralist-[0-9]*:../../print/tex-paralist
DEPENDS+=	tex-jsclasses-[0-9]*:../../print/tex-jsclasses
DEPENDS+=	tex-here-[0-9]*:../../print/tex-here
DEPENDS+=	tex-wrapfig-[0-9]*:../../print/tex-wrapfig
DEPENDS+=	tex-colortbl-[0-9]*:../../print/tex-colortbl
DEPENDS+=	tex-moreverb-[0-9]*:../../print/tex-moreverb
DEPENDS+=	dvipdfmx-[0-9]*:../../print/dvipdfmx
DEPENDS+=	tex-platex-[0-9]*:../../print/tex-platex

.include "../../mk/bsd.pkg.mk"
