# $NetBSD$

DISTNAME=       config-latex-0.05
CATEGORIES=     local-mef
MASTER_SITES=   http://cvsweb.ki.nu/mef/personal-pkgsrc
DISTFILES=      # empty

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        Set for Office work

META_PACKAGE=	yes

DEPENDS+=	tex-cjk-[0-9]*:../../print/tex-cjk
DEPENDS+=	tex-ec-[0-9]*:../../fonts/tex-ec
DEPENDS+=	tex-rsfs-[0-9]*:../../fonts/tex-rsfs
DEPENDS+=	tex-psnfss-[0-9]*:../../fonts/tex-psnfss
DEPENDS+=	tex-paralist-[0-9]*:../../print/tex-paralist
DEPENDS+=	tex-jsclasses-[0-9]*:../../print/tex-jsclasses
DEPENDS+=	tex-here-[0-9]*:../../print/tex-here
DEPENDS+=	tex-wrapfig-[0-9]*:../../print/tex-wrapfig
DEPENDS+=	tex-colortbl-[0-9]*:../../print/tex-colortbl
DEPENDS+=	tex-moreverb-[0-9]*:../../print/tex-moreverb
DEPENDS+=	dvipdfmx-[0-9]*:../../print/dvipdfmx
DEPENDS+=	tex-platex-[0-9]*:../../print/tex-platex

DEPENDS+=	tex-datetime-[0-9]*:../../print/tex-datetime
DEPENDS+=	tex-etoolbox-[0-9]*:../../devel/tex-etoolbox
DEPENDS+=	tex-xkeyval-[0-9]*:../../print/tex-xkeyval 
DEPENDS+=	tex-ifxetex-[0-9]*:../../print/tex-ifxetex 
DEPENDS+=	tex-ctable-[0-9]*:../../print/tex-ctable  
DEPENDS+=	tex-booktabs-[0-9]*:../../print/tex-booktabs
DEPENDS+=	tex-multirow-[0-9]*:../../print/tex-multirow
DEPENDS+=	tex-fontspec-[0-9]*:../../fonts/tex-fontspec

.include "../../mk/bsd.pkg.mk"
