# $NetBSD$

DISTNAME=	config-latex-0.07
CATEGORIES=	local-mef
DISTFILES=	# empty

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Meta package for Japanese LaTex Processing

META_PACKAGE=	yes

DEPENDS+=	tex-booktabs-[0-9]*:../../print/tex-booktabs
DEPENDS+=	tex-cjk-[0-9]*:../../print/tex-cjk
DEPENDS+=	tex-colortbl-[0-9]*:../../print/tex-colortbl
DEPENDS+=	tex-ctable-[0-9]*:../../print/tex-ctable
DEPENDS+=	tex-datetime-[0-9]*:../../print/tex-datetime
DEPENDS+=	tex-ec-[0-9]*:../../fonts/tex-ec
DEPENDS+=	tex-etoolbox-[0-9]*:../../devel/tex-etoolbox
DEPENDS+=	tex-fontspec-[0-9]*:../../fonts/tex-fontspec
DEPENDS+=	tex-here-[0-9]*:../../print/tex-here
DEPENDS+=	tex-iftex-[0-9]*:../../print/tex-iftex
DEPENDS+=	tex-jsclasses-[0-9]*:../../print/tex-jsclasses
DEPENDS+=	tex-moreverb-[0-9]*:../../print/tex-moreverb
DEPENDS+=	tex-multirow-[0-9]*:../../print/tex-multirow
DEPENDS+=	tex-paralist-[0-9]*:../../print/tex-paralist
DEPENDS+=	tex-platex-[0-9]*:../../print/tex-platex
DEPENDS+=	tex-psnfss-[0-9]*:../../fonts/tex-psnfss
DEPENDS+=	tex-rsfs-[0-9]*:../../fonts/tex-rsfs
DEPENDS+=	tex-wrapfig-[0-9]*:../../print/tex-wrapfig
DEPENDS+=	tex-xkeyval-[0-9]*:../../print/tex-xkeyval

DEPENDS+=	mendexk-[0-9]*:../../textproc/mendexk
DEPENDS+=	dvipdfmx-[0-9]*:../../print/dvipdfmx
DEPENDS+=	xpdf-japanese-[0-9]*:../../print/xpdf-japanese
DEPENDS+=	tex-cjk-gs-integrate-[0-9]*:../../print/tex-cjk-gs-integrate

.include "../../mk/bsd.pkg.mk"
