# $NetBSD$

DISTNAME=	config-large-set-2023.1123
CATEGORIES=	meta-pkgs

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	All set

DEPENDS+=	config-set-[0-9]*:../../local-mef/config-set
DEPENDS+=	config-desktop-[0-9]*:../../local-mef/config-desktop
DEPENDS+=	emacs-desktop-[0-9]*:../../local-mef/emacs-desktop
DEPENDS+=	config-databases-[0-9]*:../../local-mef/config-databases
DEPENDS+=	config-mail-[0-9]*:../../local-mef/config-mail
DEPENDS+=	config-server-min-[0-9]*:../../local-mef/config-server-min
DEPENDS+=	check-update-prerequisite-[0-9]*:../../local-mef/check-update-prerequisite

META_PACKAGE=	yes

.include "../../mk/bsd.pkg.mk"
