# $NetBSD$

DISTNAME=	config-R2021-0.04
CATEGORIES=	local-mef

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Meta package for wmii and skk

META_PACKAGE=	yes

DEPENDS+=	inkscape-[0-9]*:../../graphics/inkscape

DEPENDS+=	cwdiff-[0-9]*:../../textproc/cwdiff
DEPENDS+=	wdiff-[0-9]*:../../textproc/wdiff
DEPENDS+=	R2pkg-[0-9]*:../../pkgtools/R2pkg
DEPENDS+=	xournalpp-[0-9]*:../../editors/xournalpp
DEPENDS+=	irssi-[0-9]*:../../chat/irssi
DEPENDS+=	samba>=4.0:../../net/samba4
DEPENDS+=	import-package-[0-9]*:../../pkgtools/import-package
# following are for 0.02
DEPENDS+=	mplayer-[0-9]*:../../multimedia/mplayer
DEPENDS+=	gdsreader-[0-9]*:../../wip/gdsreader
DEPENDS+=	ripmime-[0-9]*:../../mail/ripmime
DEPENDS+=	qrencode-[0-9]*:../../converters/qrencode
DEPENDS+=	ssh-askpass-[0-9]*:../../security/ssh-askpass

.include "../../mk/bsd.pkg.mk"
