# $NetBSD$

DISTNAME=	config-R2021-0.01
CATEGORIES=	local-mef

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Meta package for wmii and skk

META_PACKAGE=	yes

DEPENDS+=	cwdiff-[0-9]*:../../textproc/cwdiff
DEPENDS+=	wdiff-[0-9]*:../../textproc/wdiff
DEPENDS+=	R2pkg-[0-9]*:../../pkgtools/R2pkg
DEPENDS+=	xouralpp-[0-9]*:../../editors/xournalpp
DEPENDS+=	irssi-[0-9]*:../../chat/irssi
DEPENDS+=	samba>4.0:../../net/samba4
DEPENDS+=	import-package-[0-9]*:../../pkgtools/R2pkg

.include "../../mk/bsd.pkg.mk"
