# $NetBSD$

DISTNAME=       config-recent-0.01
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        Meta package for recent interest

META_PACKAGE=   yes

DEPENDS+= kbuild-[0-9]*:../../devel/kbuild
DEPENDS+= nagios-base-[0-9]*:../../net/nagios-base
DEPENDS+= qrencode-[0-9]*:../../converters/qrencode
DEPENDS+= dasm-[0-9]*:../../cross/dasm

.include "../../mk/bsd.pkg.mk"
