# $NetBSD$

DISTNAME=	config-R2022-0.9
CATEGORIES=	local-mef

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Meta package for 2022 diff

META_PACKAGE=	yes

DEPENDS+=	mercurial-[0-9]*:../../devel/mercurial
DEPENDS+=	libkver-[0-9]*:../../pkgtools/libkver

.include "../../mk/bsd.pkg.mk"
