# $NetBSD$

DISTNAME=       config-S9-0.02
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        CAD packages


EPENDS+=	pkgin-[0-9]*:../../pkgtools/pkgin
DEPENDS+=	zsh-[0-9]*:../../shells/zsh
DEPENDS+=	sudo-[0-9]*:../../security/sudo
DEPENDS+=	rsync-[0-9]*:../../net/rsync
DEPENDS+=	cmake-[0-9]*:../../devel/cmake
DEPENDS+=	git-base-[0-9]*:../../devel/git-base
DEPENDS+=	fvwm-[0-9]*:../../wm/fvwm
DEPENDS+=	wpa_gui-[0-9]*:../../net/wpa_gui
DEPENDS+=	mozilla-rootcerts-[0-9]*:../../security/mozilla-rootcerts
DEPENDS+=	firefox-[0-9]*:../../www/firefox
DEPENDS+=	p5-gds2-[0-9]*:../../cad/p5-gds2
DEPENDS+=	klayout-[0-9]*:../../cad/klayout
DEPENDS+=	umefont-ttf-[0-9]*:../../fonts/umefont-ttf
#EPENDS+=	kbuild-[0-9]*:../../devel/kbuild
DEPENDS+=	guile20-[0-9]*:../../lang/guile20
DEPENDS+=	gnutls-[0-9]*:../../security/gnutls
#EPENDS+=	flim-[0-9]*:../../wip/flim
#EPENDS+=	semi-[0-9]*:../../devel/semi
#EPENDS+=	wl-[0-9]*:../../wip/wl-git
#EPENDS+=	tc-[0-9]*:../../wip/tc
#EPENDS+=	emacs-desktop-[0-9]*:../../local-mef/emacs-desktop
#EPENDS+=	libflashsupport-[0-9]*:../../multimedia/libflashsupport
#EPENDS+=	adobe-flash-player-[0-9]*:../../multimedia/adobe-flash-player
DEPENDS+=	alsa-plugins-pulse-[0-9]*:../../audio/alsa-plugins-pulse
DEPENDS+=	pavucontrol-[0-9]*:../../audio/pavucontrol
DEPENDS+=	pkg_rolling-replace-[0-9]*:../../pkgtools/pkg_rolling-replace
DEPENDS+=	wget-[0-9]*:../../net/wget
DEPENDS+=	sendmail-[0-9]*:../../wip/sendmail



META_PACKAGE=   yes

.include "../../mk/bsd.pkg.mk"






     
     





















