# $NetBSD$

DISTNAME=	config-ham-0.2
CATEGORIES=	meta-pkgs

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Meta package for Ham Radio

META_PACKAGE=	yes

DEPENDS+=	tqsl-[0-9]*:../../ham/trustedQSL
DEPENDS+=	xlog-[0-9]*:../../ham/xlog
DEPENDS+=	fldigi-[0-9]*:../../ham/fldigi
DEPENDS+=	gnuradio-[0-9]*:../../meta-pkgs/gnuradio
DEPENDS+=	wsjtx-[0-9]*:..;/../wip/wsjtx


.include "../../mk/bsd.pkg.mk"
