# $NetBSD$

DISTNAME=       config-tristelo-0.01
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        Meta package for wmii and skk

META_PACKAGE=   yes

DEPENDS+= wmii-[0-9]*:../../wm/wmii
DEPENDS+= skk-[0-9]*:../../inputmethod/skk
DEPENDS+= ibus-skk-[0-9]*:../../inputmethod/ibus-skk

.include "../../mk/bsd.pkg.mk"
