# $NetBSD$

DISTNAME=       config-concrete5-0.01
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        prerequisit pkg for concrete5

DEPENDS+=	sudo-[0-9]*:../../security/sudo
DEPENDS+=	pkgin-[0-9]*:../../pkgtools/pkgin
DEPENDS+=	zsh-[0-9]*:../../shells/zsh
DEPENDS+=	xfce4-wm-[0-9]*:../../wm/xfce4-wm
DEPENDS+=	mysql-server-[0-9]*:../../databases/mysql57-server
DEPENDS+=	php-[0-9]*:../../lang/php
DEPENDS+=	php[0-9]*-mysql-[0-9]*:../../databases/php-mysql
DEPENDS+=	firefox-[0-9]*:../../www/firefox
DEPENDS+=	sendmail-[0-9]*:../../wip/sendmail
DEPENDS+=	wpa_gui-[0-9]*:../../net/wpa_gui
DEPENDS+=	fvwm-[0-9]*:../../wm/fvwm
DEPENDS+=	gmake-[0-9]*:../../devel/gmake
DEPENDS+=	p5-gettext-[0-9]*:../../devel/p5-gettext
DEPENDS+=	autoconf-[0-9]*:../../devel/autoconf
DEPENDS+=	x11-links-[0-9]*:../../pkgtools/x11-links
DEPENDS+=	ap[0-9]*-php[0-9]*-[0-9]*:../../www/ap-php
DEPENDS+=	screen-[0-9]*:../../misc/screen
DEPENDS+=	rsync-[0-9]*:../../net/rsync
DEPENDS+=	dd_rescue-[0-9]*:../../sysutils/dd_rescue
DEPENDS+=	umefont-ttf-[0-9]*:../../fonts/umefont-ttf

META_PACKAGE=   yes

.include "../../mk/bsd.pkg.mk"

