# $NetBSD$

DISTNAME=	config-R2025-0.1
CATEGORIES=	local-mef

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Meta package for 2025

META_PACKAGE=	yes

DEPENDS+=	ibus-m17n-[0-9]*:../../inputmethod/ibus-m17n
DEPENDS+=	rkdeveloptool-[0-9]*:../../sysutils/rkdeveloptool
DEPENDS+=	p5-App-ClusterSSH-[0-9]*:../../security/clusterssh


.include "../../lang/python/pyversion.mk"
.include "../../mk/bsd.pkg.mk"
