# $NetBSD$

DISTNAME=	config-R2026-0.2
CATEGORIES=	local-mef

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Meta package for 2026

META_PACKAGE=	yes

DEPENDS+=	nodejs-[0-9]*:../../lang/nodejs
DEPENDS+=	php[0-9]*-composer-[0-9]*:../../devel/php-composer
DEPENDS+=	bob-[0-9]*:../../pkgtools/bob
DEPENDS+=	config-selenium-[0-9]*:../../local-mef/config-selenium
DEPENDS+=	freerdp2-[0-9]*:../../net/freerdp2
#EPENDS+=	wine-[0-9]*:../../emulators/wine
DEPENDS+=	ripmime-[0-9]*:../../mail/ripmime

.include "../../mk/bsd.pkg.mk"
