# $NetBSD$

DISTNAME=	config-R2026-0.1
CATEGORIES=	local-mef

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Meta package for 2026

META_PACKAGE=	yes

DEPENDS+=	nodejs-[0-9]*:../../lang/nodejs
DEPENDS+=	php[0-9]*-composer-[0-9]*:../../devel/php-composer

.include "../../mk/bsd.pkg.mk"
