# $NetBSD$

DISTNAME=       config-databases-2025.04
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://github.com/makoto-fujiwara/local-mef/config-databases
COMMENT=        Small set of databases packages

DEPENDS+=	postgresql[0-9]*-client-[0-9]*:../../databases/postgresql17-client
DEPENDS+=	p5-DBI-[0-9]*:../../databases/p5-DBI


META_PACKAGE=   yes

.include "../../mk/bsd.pkg.mk"
