# $NetBSD$

DISTNAME=       config-devel-0.01
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        Meta package for developing pkgsrc

META_PACKAGE=   yes

DEPENDS+=	checkperms-[0-9]*:../../sysutils/checkperms
DEPENDS+=	calltree-perl-[0-9]*:../../devel/calltree-perl
DEPENDS+=	doxygen-[0-9]*:../../devel/doxygen
DEPENDS+=	pkglint-[0-9]*:../../pkgtools/pkglint
DEPENDS+=	revbump-[0-9]*:../../pkgtools/revbump
DEPENDS+=	x11-links-[0-9]*:../../pkgtools/x11-links


.include "../../mk/bsd.pkg.mk"
