# $NetBSD$

DISTNAME=	config-R2024-0.2
CATEGORIES=	local-mef

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Meta package for 2023

META_PACKAGE=	yes

DEPENDS+=	opendkim-[0-9]*:../../mail/opendkim
DEPENDS+=	py-pypi-cli-[0-9]*:../../devel/py-pypi-cli
DEPENDS+=	minicom-[0-9]*:../../comms/minicom

.include "../../mk/bsd.pkg.mk"
