# $NetBSD$

DISTNAME=       config-meta-pkgs-0.1
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        More meta-pkgs

BUILD_DEPENDS+= netbsd-www-[0-9]*:../../meta-pkgs/netbsd-www	
BUILD_DEPENDS+= xfce4-[0-9]*:../../meta-pkgs/xfce4
BUILD_DEPENDS+= xfce4-extras-[0-9]*:../../meta-pkgs/xfce4-extras

META_PACKAGE=   yes

.include "../../mk/bsd.pkg.mk"
