# $NetBSD$

DISTNAME=       config-startup-0.3
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        Meta package for monitoring machine

META_PACKAGE=   yes

DEPENDS+= git-base-[0-9]*:../../devel/git-base
DEPENDS+= screen-[0-9]*:../../misc/screen
DEPENDS+= rsync-[0-9]*:../../net/rsync
DEPENDS+= wget-[0-9]*:../../net/wget
DEPENDS+= cwrappers-[0-9]*:../../pkgtools/cwrappers
DEPENDS+= digest-[0-9]*:../../pkgtools/digest
#EPENDS+= pkgin-[0-9]*:../../pkgtools/pkgin
DEPENDS+= sudo-[0-9]*:../../security/sudo
DEPENDS+= zsh-[0-9]*:../../shells/zsh
DEPENDS+= checkperms-[0-9]*:../../sysutils/checkperms
DEPENDS+= sendmail-[0-9]*:../../mail/sendmail
DEPENDS+= fvwm-[0-9]*:../../wm/fvwm

.include "../../mk/bsd.pkg.mk"
