# $NetBSD$

DISTNAME=	config-inputmethod-0.2025.08
CATEGORIES=	meta-pkgs

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Inputmethos

META_PACKAGE=	yes

#EPENDS+=	mozc-elisp-[0-9]*:../../inputmethod/mozc-elisp
#EPENDS+=	mozc-renderer-[0-9]*:../../inputmethod/mozc-renderer
#EPENDS+=	mozc-server-[0-9]*:../../inputmethod/mozc-server
#EPENDS+=	mozc-tool-[0-9]*:../../inputmethod/mozc-tool
#EPENDS+=	ibus-tutcode-[0-9]*:../../wip/ibus-tutcode
DEPENDS+=	ibus-m17n-[0-9]*:../../inputmethod/ibus-m17n

.include "../../mk/bsd.pkg.mk"
