# $NetBSD$

DISTNAME=	config-inputmethod-0.2024.07
CATEGORIES=	meta-pkgs

MAINTAINER=	packages@ki.nu
HOMEPAGE=	http://www.ki.nu/OHP/
COMMENT=	Inputmethos

META_PACKAGE=	yes

DEPENDS+=	mozc-elisp-[0-9]*:../../inputmethod/mozc-elisp
DEPENDS+=	mozc-renderer-[0-9]*:../../inputmethod/mozc-renderer
DEPENDS+=	mozc-server-[0-9]*:../../inputmethod/mozc-server
DEPENDS+=	mozc-tool-[0-9]*:../../inputmethod/mozc-tool
DEPENDS+=	ibus-tutcode-[0-9]*:../../wip/ibus-tutcode

.include "../../mk/bsd.pkg.mk"
