# $NetBSD$

DISTNAME=	test-git-2.13.2
CATEGORIES=	meta-pkgs
LICENSE=	generic-nonlicense

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Collection of git family to test

META_PACKAGE=	YES

BUILD_DEPENDS+=	git-base-[0-9]*:../../devel/git-base
BUILD_DEPENDS+=	git-contrib-[0-9]*:../../devel/git-contrib/
BUILD_DEPENDS+=	git-docs-[0-9]*:../../devel/git-docs/
BUILD_DEPENDS+=	git-gitk-[0-9]*:../../devel/git-gitk/
BUILD_DEPENDS+=	gitweb-[0-9]*:../../www/gitweb/

.include "../../mk/bsd.pkg.mk"

