# $NetBSD$

DISTNAME=       config-cad-2021.10
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        CAD packages

DEPENDS+=	klayout-[0-9]*:../../cad/klayout
DEPENDS+=	p5-gds2-[0-9]*:../../cad/p5-gds2
DEPENDS+=	p5-GD-[0-9]*:../../graphics/p5-GD
DEPENDS+=	gdsreader-[0-9]*:../../wip/gdsreader
DEPENDS+=	kicad-[0-9]*:../../cad/kicad
#EPENDS+=	eagle-[0-9]*:../../cad/eagle
DEPENDS+=	qcad-[0-9]*:../../cad/qcad
DEPENDS+=	py[0-9]*-picture-to-gds-[0-9]*:../../wip/py-picture-to-gds
DEPENDS+=	py[0-9]*-gds-[0-9]*:../../cad/py-gds


META_PACKAGE=   yes

.include "../../mk/bsd.pkg.mk"
