# $NetBSD$

DISTNAME=       config-cad-2024.08
CATEGORIES=     meta-pkgs

MAINTAINER=     packages@ki.nu
HOMEPAGE=       http://www.ki.nu/OHP/
COMMENT=        CAD packages

DEPENDS+=	klayout-[0-9]*:../../cad/klayout
DEPENDS+=	p5-gds2-[0-9]*:../../cad/p5-gds2
DEPENDS+=	p5-GD-[0-9]*:../../graphics/p5-GD
DEPENDS+=	gdsreader-[0-9]*:../../wip/gdsreader
DEPENDS+=	kicad-[0-9]*:../../cad/kicad
#EPENDS+=	eagle-[0-9]*:../../cad/eagle
#EPENDS+=	qcad-[0-9]*:../../cad/qcad
#EPENDS+=	py[0-9]*-picture-to-gds-[0-9]*:../../wip/py-picture-to-gds

DEPENDS+=	py[0-9]*-gdstk-[0-9]*:../../cad/py-gdstk
DEPENDS+=	fstl-[0-9]*:../../cad/fstl
DEPENDS+=	openscad-[0-9]*:../../cad/openscad
DEPENDS+=	gwyddion-[0-9]*:../../wip/gwyddion


META_PACKAGE=   yes

.include "../../mk/bsd.pkg.mk"
