# $NetBSD$

DISTNAME=	webmin-test-1.8.31
CATEGORIES=	meta-pkgs
LICENSE=	generic-nonlicense

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Collection of webmin family to test

META_PACKAGE=	YES

BUILD_DEPENDS+=	wbm-apache-[0-9]*:../../sysutils/wbm-apache
BUILD_DEPENDS+=	wbm-at-[0-9]*:../../sysutils/wbm-at
BUILD_DEPENDS+=	wbm-bandwidth-[0-9]*:../../sysutils/wbm-bandwidth
BUILD_DEPENDS+=	wbm-bind8-[0-9]*:../../sysutils/wbm-bind8
BUILD_DEPENDS+=	wbm-change-user-[0-9]*:../../sysutils/wbm-change-user
BUILD_DEPENDS+=	wbm-cluster-copy-[0-9]*:../../sysutils/wbm-cluster-copy
BUILD_DEPENDS+=	wbm-cluster-cron-[0-9]*:../../sysutils/wbm-cluster-cron
BUILD_DEPENDS+=	wbm-cluster-passwd-[0-9]*:../../sysutils/wbm-cluster-passwd
BUILD_DEPENDS+=	wbm-cluster-shell-[0-9]*:../../sysutils/wbm-cluster-shell
BUILD_DEPENDS+=	wbm-cluster-useradmin-[0-9]*:../../sysutils/wbm-cluster-useradmin
BUILD_DEPENDS+=	wbm-cluster-webmin-[0-9]*:../../sysutils/wbm-cluster-webmin
BUILD_DEPENDS+=	wbm-custom-[0-9]*:../../sysutils/wbm-custom
BUILD_DEPENDS+=	wbm-cyrus-imapd-[0-9]*:../../sysutils/wbm-cyrus-imapd
BUILD_DEPENDS+=	wbm-dhcpd-[0-9]*:../../sysutils/wbm-dhcpd
BUILD_DEPENDS+=	wbm-dovecot-[0-9]*:../../sysutils/wbm-dovecot
BUILD_DEPENDS+=	wbm-fetchmail-[0-9]*:../../sysutils/wbm-fetchmail
BUILD_DEPENDS+=	wbm-file-[0-9]*:../../sysutils/wbm-file
BUILD_DEPENDS+=	wbm-htaccess-htpasswd-[0-9]*:../../sysutils/wbm-htaccess-htpasswd
BUILD_DEPENDS+=	wbm-inetd-[0-9]*:../../sysutils/wbm-inetd
BUILD_DEPENDS+=	wbm-ipfilter-[0-9]*:../../sysutils/wbm-ipfilter
BUILD_DEPENDS+=	wbm-ldap-useradmin-[0-9]*:../../sysutils/wbm-ldap-useradmin
BUILD_DEPENDS+=	wbm-lpadmin-[0-9]*:../../sysutils/wbm-lpadmin
BUILD_DEPENDS+=	wbm-mailboxes-[0-9]*:../../sysutils/wbm-mailboxes
BUILD_DEPENDS+=	wbm-mount-[0-9]*:../../sysutils/wbm-mount
BUILD_DEPENDS+=	wbm-mysql-[0-9]*:../../sysutils/wbm-mysql
BUILD_DEPENDS+=	wbm-net-[0-9]*:../../sysutils/wbm-net
BUILD_DEPENDS+=	wbm-openslp-[0-9]*:../../sysutils/wbm-openslp
#UILD_DEPENDS+=	wbm-passwd-[0-9]*:../../sysutils/wbm-passwd
BUILD_DEPENDS+=	wbm-postfix-[0-9]*:../../sysutils/wbm-postfix
BUILD_DEPENDS+=	wbm-postgresql-[0-9]*:../../sysutils/wbm-postgresql
BUILD_DEPENDS+=	wbm-qmailadmin-[0-9]*:../../sysutils/wbm-qmailadmin
BUILD_DEPENDS+=	wbm-quota-[0-9]*:../../sysutils/wbm-quota
BUILD_DEPENDS+=	wbm-sendmail-[0-9]*:../../sysutils/wbm-sendmail
BUILD_DEPENDS+=	wbm-shell-[0-9]*:../../sysutils/wbm-shell
BUILD_DEPENDS+=	wbm-sshd-[0-9]*:../../sysutils/wbm-sshd
BUILD_DEPENDS+=	wbm-status-[0-9]*:../../sysutils/wbm-status
BUILD_DEPENDS+=	wbm-syslog-[0-9]*:../../sysutils/wbm-syslog
BUILD_DEPENDS+=	wbm-telnet-[0-9]*:../../sysutils/wbm-telnet
BUILD_DEPENDS+=	wbm-time-[0-9]*:../../sysutils/wbm-time
BUILD_DEPENDS+=	wbm-tunnel-[0-9]*:../../sysutils/wbm-tunnel
BUILD_DEPENDS+=	wbm-useradmin-[0-9]*:../../sysutils/wbm-useradmin
BUILD_DEPENDS+=	wbm-virtual-server-[0-9]*:../../sysutils/wbm-virtual-server
BUILD_DEPENDS+=	webmin-[0-9]*:../../sysutils/webmin

.include "../../mk/bsd.pkg.mk"

